### ISSUE TITLE
[FE - inspect page] Couldn't select Figure elements in "inspect-document" section

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/verapdf-webapp-gui#105]
[TableWithImages.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4758386/TableWithImages.pdf)

1. Upload attached PDF and inspect it
2. Try to select Figure elements in "inspect-document" section

**Actual result:** Couldn't select Figure elements 
![img2](https://user-images.githubusercontent.com/59257413/84267509-d6deea80-ab2e-11ea-8b6d-764ebb14998c.png)

**Expected result:** All structure elements in items may be selected

**Comment by MarinaSaroka** [comment]
Verified
