### ISSUE TITLE
[FE] Incorrect bounding box for content

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/verapdf-webapp-gui#107]
[ET04_PDFUA_The_Standard_for_Accessible_PDF.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4758660/ET04_PDFUA_The_Standard_for_Accessible_PDF.pdf)

1. Upload attached PDF and inspect it
2. Scroll to the end of document in "inspect-document" section
3. Select "Page 17: 3 of 3"

**Actual result:** 
![image](https://user-images.githubusercontent.com/59257413/84272179-c120f380-ab35-11ea-87c4-dc6d4234c222.png)
**Expected result:** bbox for content shall be correct

**Comment by MarinaSaroka** [comment]
Verified
