### ISSUE TITLE
[FE - summary-tree] Couldn't expand checks for more than one rule

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/verapdf-webapp-gui#110]
[7.1-t01-fail-a.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4770366/7.1-t01-fail-a.pdf)

1. Upload PDF and inspect it on default profile
2. Try to expand two rules to see see all checks together

**Actual result:** Only checks for one rule may be expanded
**Expected result:**  More than one rules may be expanded together to see checks

**Comment by MarinaSaroka** [comment]
Done
