### ISSUE TITLE
[FE - Inspect Page] Return to "Upload Page" after clear browsing data and clicking on refresh

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/verapdf-webapp-gui#113]
[testFile.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4819324/testFile.pdf)

1. Upload atached PDF with default profile
2. Open Inspect page
3. Clear browsing data and refresh inspect page

**Actual result:** application is crashed
**Expected result:** Upload page is present on the front

**Comment by MarinaSaroka** [comment]
Verified
