### ISSUE TITLE
[FE - result summary] Change "errors" to "checks failed" the same as GUI

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/verapdf-webapp-gui#115]
[7.21.7-t01-fail-a.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4824604/7.21.7-t01-fail-a.pdf)

1. Validate attached PDF on Machine Profile
2. Look at summary

**Actual result:** "errors" are present
**Expected result:** "checks_failed" instead "errors" are present 
![gui](https://user-images.githubusercontent.com/59257413/85537053-4ddead80-b61c-11ea-9858-884ebe86668f.png)

**Comment by bdoubrov** [comment]
Errors seems to be more clear to the users than failed checks.
