### ISSUE TITLE
[FE - validationErrorMessages.json] Fix typo in 7.18.4-1 rule about widget annotation

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/verapdf-webapp-gui#117]
![interactive](https://user-images.githubusercontent.com/59257413/85566521-cc494880-b638-11ea-85b8-592d4e83cb60.png)

**Expected result:** _Dynamic_ shall be change to _Interactive_

**Comment by MarinaSaroka** [comment]
Verified
