### ISSUE TITLE
Seeking clarification around features.xml fields

### ISSUE THREAD

**Issue by ross-spencer** [veraPDF/verapdf-webapp-gui#134]
I have a `config/features.xml` from VeraPDF 1.16.1 and if I compare it to the docs today: https://docs.verapdf.org/cli/config/#features.xml there are three changes - `ACTION` and `INTERACTIVE_FORM_FIELDS` are no longer there, and `ERROR` is added. Is that the correct state, i.e. those two fields removed and the others added? 

```diff
index 024237d..cf687e3 100644
--- a/features.xml
+++ b/features.xml
@@ -1,6 +1,5 @@
 <featuresConfig>
     <enabledFeatures>
-        <feature>ACTION</feature>
         <feature>ANNOTATION</feature>
         <feature>COLORSPACE</feature>
         <feature>DOCUMENT_SECURITY</feature>
@@ -11,7 +10,6 @@
         <feature>ICCPROFILE</feature>
         <feature>IMAGE_XOBJECT</feature>
         <feature>INFORMATION_DICTIONARY</feature>
-        <feature>INTERACTIVE_FORM_FIELDS</feature>
         <feature>LOW_LEVEL_INFO</feature>
         <feature>METADATA</feature>
         <feature>OUTLINES</feature>
@@ -22,5 +20,6 @@
         <feature>PROPERTIES</feature>
         <feature>SHADING</feature>
         <feature>SIGNATURE</feature>
+        <feature>ERROR</feature>
     </enabledFeatures>
 </featuresConfig>
```

Additionally, out of interest, I was wondering what the features.xml in the 1.18 branch does and where it is used as it seems to adopt a different schema: https://github.com/veraPDF/veraPDF-apps/blob/rel/1.18/installer/src/main/config/features.xml 

_PS. Is there a better way to ask this question? And is this the global repo for any VeraPDF issues?_

**Comment by bdoubrov** [comment]
Generally, configuring feature extraction is documented here: https://docs.verapdf.org/cli/feature-extraction/

The file features.xml in the [veraPDF-apps](https://github.com/veraPDF/veraPDF-apps/blob/rel/1.18/installer/src/main/config/features.xml) repo is only used as an initial configuration used after the installation. But one can freely edit this file manually or even use the GUI to do this (menu item Configs->Features Config in the GUI). 

To ask general questions on veraPDF you can subscribe to the veraPDF mailing list at: http://lists.verapdf.org/listinfo/users . Alternatively, you can always report any issues at https://github.com/veraPDF/veraPDF-library .
