### ISSUE TITLE
[FE]: Inspect errors in specific PDF document

### ISSUE THREAD

**Issue by yuliya-ivaniukovich** [veraPDF/verapdf-webapp-gui#18]
Render list of errors and PDF next to it.
Selecting error occurrence in the should highlight corresponding bbox in PDF (navigating to the page if needed) and vice versa (scroll and expand of corresponding error node in tree should happen). 

In scope of this task we will display **only one page at a time**, pages will be switched using simple buttons "Next page", "Previous page".

Overlays should be displayed as `div` elements, **no zooming** for now.

_TECH NOTES_: 
Do not use `jquery` or `document.querySelector`. When page is rendered call `getOperatorsList` and update state with bbox info. This should trigger component re-rendering and overlays should be rendered during regular component render phase. 

Make sure not to update state if there are no changes in bbox results to avoid circular re-rendering.

Pass the list of MCID's for which overlays should be rendered as a parameter `filter` (function) to custom component which is responsible for rendering page with related overlays (named e.g. `TaggedPage`).

Expected commits structure:
 - [ ] render list of errors (no info button for now)
 - [ ] add info button which should open detailed error info modal
 - [ ] render first PDF page
 - [ ] add page navigation buttons at the bottom
 - [ ] select error occurrence should navigate to page and highlight bbox overlay
 - [ ] select bbox overlay should select occurrence in the list
 - [ ] add automatic scrolling and expanding error for the case when occurrence is not visible

Every commit should include minimal integration test(s) (or extend existing tests) to cover only positive cases for now.
Request review as soon as there is new commit ready to speed up process and avoid too much rework.

**Comment by bdoubrov** [comment]
Implemented as specified
