### ISSUE TITLE
[FE - Inspect Page] Some files don't fit in inspect page when scale is 150%

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/verapdf-webapp-gui#51]
[ET04_PDFUA_The_Standard_for_Accessible_PDF.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4710703/ET04_PDFUA_The_Standard_for_Accessible_PDF.pdf)

**Comment by yuliya-ivaniukovich** [comment]
To be addressed after https://github.com/veraPDF/verapdf-webapp-gui/issues/29
