### ISSUE TITLE
[FE - Upload page/dropzone] Change dropzone-text

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/verapdf-webapp-gui#53]
Now our dropzone-text looks like that: "Drop some PDF files here, or click to select files"

Should be: "Drop a PDF file, or click to select a file"

**Should be fixed typo after _file_**

**Comment by Resip10** [comment]
Due to grammar rules commas should be placed before “Or” for two independent clauses
https://www.grammarly.com/blog/comma-before-or/
