### ISSUE TITLE
[FE - Select Settings]: Dropdown list is shifted

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/verapdf-webapp-gui#58]
Steps to reproduce:

1. Tagged PDF is selected
2. Open dropdown list to select another profile

**Actual Result:** dropdown list is shifted
![img](https://user-images.githubusercontent.com/59257413/83400844-4278d780-a40c-11ea-9bea-672e5ef9b5cb.png)
**Expected Result:** dropdown list is not shifted and selected profile is highlighted

**Comment by yuliya-ivaniukovich** [comment]
Behavior is expected, it's adapted to small screens
