### ISSUE TITLE
Setup production stack

### ISSUE THREAD

**Issue by yuliya-ivaniukovich** [veraPDF/verapdf-webapp-gui#70]
Setup Prod stack to be available at https://verapdf.duallab.com/

[ ] Setup a repository for our webapp project in Docker Hub - **Yuliya**
[ ] Investigate how to publish images on Docker Hub - **Artem**
[ ] Publish tagged version for further deployment to prod - **Yuliya or Artem**
[ ] Setup docker compose stack to rollout prod instance and configure proxy NGINX to point there. - **Yuliya and Artem**

**Comment by bdoubrov** [comment]
Implemented via GitHub actions
