### ISSUE TITLE
[FE - Inspect Page] Improve aspect ratio of PDF file on inspect page

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/verapdf-webapp-gui#94]
[7.3-t01-fail-a.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4756843/7.3-t01-fail-a.pdf)

1. Upload PDF and open inspect-page
2. Set 150% scale

**Actual result:** Aspect ratio looks like on image
![scale_150](https://user-images.githubusercontent.com/59257413/84239923-eac22680-ab05-11ea-9069-ced2c5fe5d9f.png)
**Expected result:** No pixels on PDF file with scale 150%

**Comment by Resip10** [comment]
Depends on #29 . Aspect ratio event will be redirected to implemented zoom
